# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: neochat
    env: node
    plan: free # o el plan que prefieras
    region: oregon # o la región que prefieras
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # Debes establecer esto en el dashboard de Render
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    healthCheckPath: /
